check for conflicting branches
When dealing with hierarchical branch names that contain slashes, they
are mapped to directories and files below .git/refs. This makes it
impossible to have a branch aur when there already is a branch starting
with aur/ and vice versa.

As offremote will work fine in this case, the fetch command is the first
to fail. To not break with only the last step not correctly performed,
leaving the repository invoked on in an unexpected state, this is now
checked beforehand to stop any action to begin with.

It also implicitly warns the user when a -c flag is most probably
missing or superfluous.

diff --git a/auradopt b/auradopt
--- a/auradopt
+++ b/auradopt
@@ -10,7 +10,7 @@ do
       echo ' -h  show this help text'
       echo ' -c  include the name of the package in branch and remote name'
       exit ;;
-    c) name=/ ;;
+    c) name= ;;
     \?) exit 1 ;;
   esac
 done
@@ -22,7 +22,17 @@ then
   gettext -sd bash 'argument expected'
   exit 1
 fi
+readonly conflicts="aur${name-/*}"
 readonly name="aur${name+/${package}}"
+
+# Check conflicting branches.
+if [ -n "$(git branch --list "$conflicts")" ]
+then
+  TEXTDOMAIN=git printf "$(gettext "cannot create '%s'"): $(
+    gettext "A branch named '%s' already exists.")\n" \
+    "$name" "$conflicts" >&2
+  exit 1
+fi
 
 # Prepare branch.
 offremote -n "$name" \
